pipeline {
    agent any

    environment {
        IMAGE_NAME = "hariabjayon15/flask-app"
        BUILD_TAG = "${BUILD_NUMBER}"
    }

    stages {
        stage('Checkout Code') {
            steps {
                script {
                    echo "Workspace directory: ${env.WORKSPACE}"
                    echo "Checking for project directory: ${env.WORKSPACE}\\project-1"
                    if (!fileExists("${env.WORKSPACE}\\project-1")) {
                        error "ERROR: Project directory missing!"
                    }
                }
            }
        }

        stage('Login to Docker Hub') {
            steps {
                script {
                    withCredentials([usernamePassword(credentialsId: 'docker-hub-token', usernameVariable: 'DOCKER_USER', passwordVariable: 'DOCKER_PASS')]) {
                         bat """
                         echo %DOCKER_PASS% | docker login -u %DOCKER_USER% --password-stdin
                         """
                    }
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    echo "Building Docker image..."
                    dir('project-1') {
                        powershell """
                        docker pull python:3.11-slim
                        docker build -t ${IMAGE_NAME}:${BUILD_TAG} .
                        docker tag ${IMAGE_NAME}:${BUILD_TAG} ${IMAGE_NAME}:latest
                        """
                    }
                }
            }
        }

        stage('Push to Docker Hub') {
            steps {
                script {
                    powershell """
                    docker push ${IMAGE_NAME}:${BUILD_TAG}
                    docker push ${IMAGE_NAME}:latest
                    """
                }
            }
        }
    }

    post {
        failure {
            echo "❌ Build failed. Please check the logs."
        }
    }
}
